# Dockerfile.dev
# Use the official Go image for development
FROM golang:1.23-alpine

# Install necessary dependencies
RUN apk add --no-cache git

# Set working directory
WORKDIR /usr/src/app

# Copy Go module files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Install air for hot-reloading
RUN go install github.com/air-verse/air@latest

# Copy the source code
COPY . .

# Expose application port
EXPOSE 8080

# Start server with air for hot reloading
CMD ["air", "-c", ".air.toml"]