version: '3.8'

services:
  app:
    container_name: go-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/tmp
    env_file:
      - .env
    command: ["air", "-c", ".air.toml"]